# Generated by Django 2.2.1 on 2019-06-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyServer', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
    ]
